### ISSUE TITLE
模块加载问题

### ISSUE THREAD

**Issue by hucoooo** [imouou/buijs-cli#2]
使用router.loadPart加载局部模块，底部导航mian.js中的mod.init()；报错，打印mod为空

**Comment by qq702482502** [comment]
> 使用router.loadPart加载局部模块，底部导航mian.js中的mod.init()；报错，打印mod为空
loader.require(["pages/main/home"],function (mod) {
     // 有回调的话是每次切换都会触发
     mod.init();
})

**Comment by hucoooo** [comment]
loader.require(["pages/main/home"],function (mod) {
    // 有回调的话是每次切换都会触发
    mod.init();
})

**Comment by imouou** [comment]
router.loadPart 是用于局部加载模板,如果有脚本会顺带执行, 相当于 router.load , 只是一个是在当前页的某个id里,一个是新开页面;
loader.require 是加载某个模块, 默认没有回调的话是会缓存, 也就是继续 require, 不会重新请求, 当你有回调的时候, 每次都会执行这个回调, 而这个回调可以拿到你加载模块的上下文的方法, 也就是你的home要return 出 一个init 方法才会有. 

这个路由及模块可以实现很多复杂的组合及需求.  具体可以下载案例理解

**Comment by hucoooo** [comment]
有供交流的群吗？

**Comment by imouou** [comment]
具体查看官网的文档吧 www.easybui.com
