### ISSUE TITLE
cli工具执行buijs create demo3报错如下

### ISSUE THREAD

**Issue by xeon-ye** [imouou/buijs-cli#5]
/usr/local/lib/node_modules/buijs/buijs-cli.js:387
                    package.scripts[`dev-${name}`] = `cross-env NODE_ENV=${name} gulp dev`;
                                                   ^

TypeError: Cannot set property 'dev-demo3' of undefined
    at modifyPackage (/usr/local/lib/node_modules/buijs/buijs-cli.js:387:52)
    at /usr/local/lib/node_modules/buijs/buijs-cli.js:299:17

**Comment by imouou** [comment]
你是想创建一个bui的工作目录？NODE几？12-16？里面的依赖限制了node的版本只能在某个区间，也可以换个目录试试，看报错貌似是存在package.json 且不可修改的问题，确保有这个目录的操作权限。单独创建一个工程应该是没问题的

**Comment by xeon-ye** [comment]
切到17成功了，谢谢
zonesoft@yedeMacBook-Pro  ~  buijs create bui-demo -t main-tab
INFO Creating project...
INFO Fetching release: latest...
INFO Already cached release.
INFO Copying default template file...
INFO Copying template file.
INFO Initing template...
INFO Copy template done.
INFO Copy Dev done.
INFO Project created done.
 zonesoft@yedeMacBook-Pro  ~  nvm list
    iojs-v3.3.1
       v12.22.6
       v14.18.0
->      v17.1.0
         system
default -> v12.22.6
unstable -> N/A (default)
node -> stable (-> v17.1.0) (default)
stable -> 17.1 (-> v17.1.0) (default)
iojs -> iojs-v3.3 (-> iojs-v3.3.1) (default)
lts/* -> lts/gallium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1 (-> N/A)
lts/erbium -> v12.22.7 (-> N/A)
lts/fermium -> v14.18.2 (-> N/A)
lts/gallium -> v16.13.1 (-> N/A)
 zonesoft@yedeMacBook-Pro  ~ 

**Comment by xeon-ye** [comment]
npm run start报错了

**Comment by xeon-ye** [comment]
zonesoft@yedeMacBook-Pro  ~/bui-demo  npm run dev

> buiapp@1.0.0 dev
> gulp dev

[09:38:14] Using gulpfile ~/bui-demo/gulpfile.js
[09:38:14] Starting 'dev'...
[09:38:14] Starting 'move'...
[09:38:14] Finished 'move' after 133 ms
[09:38:14] Starting 'html'...
[09:38:14] Finished 'html' after 14 ms
[09:38:14] Starting 'css'...
[09:38:14] Finished 'css' after 3.96 ms
[09:38:14] Starting 'images'...
[09:38:14] Finished 'images' after 14 ms
[09:38:14] Starting 'less'...
[09:38:14] Finished 'less' after 6.45 ms
[09:38:14] Starting 'babel'...
[09:38:15] 'babel' errored after 515 ms
[09:38:15] SyntaxError in plugin "gulp-babel"
Message:
    **/Users/zonesoft/bui-demo/src/node/node10-sass/gulpfile.js: Unexpected reserved word 'package'. (70:6)**

  68 | const ip = getNetwork().ip || "localhost";
  69 | // 读取配置
> 70 | const package = require('./package.json');
     |       ^
  71 | // 起服务
  72 | var browserSync = require('browser-sync').create();
  73 | var reload = browserSync.reload;

**Comment by xeon-ye** [comment]
eslint规则冲突，貌似环境换成最新的LTS版本后没问题了
